// package ExceptionHandling;

// public class variousExceptions {
//     public static void main(String[] args) {
        
//         int[] array1 = {1,2,3,4,5};
//         int[] array2 = {1,2,3,4,5};

//         int[] result = null;

//         try 
//             {
//                 for(int i=0;i<5;i++)
//                     {
//                         result[i] = array1[i] / array2[i];
//                     }
//             }
//         catch(ArithmeticException e)
//             {
//                 System.out.println("Catch block with arithmetic exception is executed");
//             }
//         catch(NullPointerException e)
//             {
//                 System.out.println("Catch block with Null Pointer Exception is executed");
//             }
//         catch(ArrayIndexOutOfBoundsException e)
//             {
//                 System.out.println("Catch block with Array Index Out of Bounds Exception is Executed");
//             }
//         catch(NumberFormatException e)
//             {
//                 System.out.println("CAtch block with Number Format Exception is executed");
//             }
        
//     }
// }
